/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#00486d',
          container: '#006190',
          fixed: '#cbe6ff',
          'fixed-dim': '#8ecdff',
        },
        secondary: {
          DEFAULT: '#006494',
          container: '#71c3ff',
          fixed: '#cae6ff',
          'fixed-dim': '#8ecdff',
        },
        tertiary: {
          DEFAULT: '#004f1c',
          container: '#006a28',
          fixed: '#9af8a2',
          'fixed-dim': '#7edb89',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        cta: {
          DEFAULT: '#3D95CE',
        },
        'telegram-blue': '#2AABEE',
        background: '#f9f9fa',
        surface: {
          DEFAULT: '#f9f9fa',
          dim: '#dadadb',
          bright: '#f9f9fa',
          variant: '#e2e2e3',
          tint: '#006494',
          container: {
            DEFAULT: '#eeeeef',
            low: '#f3f3f4',
            lowest: '#ffffff',
            high: '#e8e8e9',
            highest: '#e2e2e3',
          },
        },
        outline: {
          DEFAULT: '#707880',
          variant: '#bfc7d1',
        },
        on: {
          primary: '#ffffff',
          'primary-container': '#add9ff',
          'primary-fixed': '#001e30',
          'primary-fixed-variant': '#004b71',
          secondary: '#ffffff',
          'secondary-container': '#005077',
          'secondary-fixed': '#001e30',
          'secondary-fixed-variant': '#004b70',
          tertiary: '#ffffff',
          'tertiary-container': '#8be894',
          background: '#1a1c1d',
          surface: '#1a1c1d',
          'surface-variant': '#40484f',
          error: '#ffffff',
          'error-container': '#93000a',
        },
        text: {
          primary: '#1a1c1d',
          secondary: '#40484f',
          muted: '#707880',
        },
        brand: {
          DEFAULT: '#00486d',
          light: '#006190',
          muted: '#096493',
        },
        success: '#006a28',
        danger: '#ba1a1a',
        'surface-dark': '#f9f9fa',
        'surface-card': '#ffffff',
        'surface-border': '#e2e2e3',
      },
      borderRadius: {
        card: '24px',
      },
      spacing: {
        'stack-gap-sm': '8px',
        'stack-gap-md': '16px',
        'stack-gap-lg': '24px',
        'edge-margin': '16px',
        'container-padding': '20px',
      },
      fontSize: {
        'display-amount': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-amount-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-sm-mobile': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'section-label': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '800' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      boxShadow: {
        tactile: 'none',
        card: 'none',
        ambient: 'none',
      },
    },
  },
  plugins: [],
};
